name: Release

on:
  workflow_run:
    workflows: ["Test"]
    branches:
      - master
      - dev
    types: ["completed"]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      GOROOT: /usr/local/go
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get service name
        id: service
        run: echo "::set-output name=service::$(git describe --tags|sed -e 's/\-v.*//')"

      - name: Get service version
        id: version
        run: echo "::set-output name=version::$(git describe --tags|sed -e 's/.*\-v//')"

      - run: echo "::warning ::Release ${{ steps.service.outputs.service }} v${{ steps.version.outputs.version }}"

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          install-only: true

      # odysee-api specific section

      - name: Build odysee-api
        if: steps.service.outputs.service == 'api'
        run: |
          go get github.com/gobuffalo/packr/v2/packr2@v2.7.1
          goreleaser --rm-dist --snapshot

      - name: Build odysee-api docker image
        if: steps.service.outputs.service == 'api'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: lbry/odysee-api
          tags: latest,${{ steps.version.outputs.version }}

      - name: Deploy odysee-api
        if: steps.service.outputs.service == 'api'
        uses: octokit/request-action@v2.x
        id: deploy-odysee-api
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYMENT_REPO_TOKEN }}
        with:
          route: POST /repos/:repository/dispatches
          repository: lbryio/lbrytv-deployment
          event_type: deploy-odysee-api
          client_payload: |
            tag: ${{ steps.version.outputs.version }}
            ref: ${{ github.ref }}
            service: odysee-api

      # lbrytv-collector specific section

      - name: Build lbrytv-collector
        if: steps.service.outputs.service == 'collector'
        run: |
          go get github.com/markbates/pkger/cmd/pkger
          make collector

      - name: Build lbrytv-collector docker image
        if: steps.service.outputs.service == 'collector'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: lbry/lbrytv-${{ steps.service.outputs.service }}
          tags: latest,${{ steps.version.outputs.version }}
          dockerfile: apps/${{ steps.service.outputs.service }}/Dockerfile

      - name: Deploy lbrytv-collector
        if: steps.service.outputs.service == 'collector'
        uses: octokit/request-action@v2.x
        id: deploy-collector
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYMENT_REPO_TOKEN }}
        with:
          route: POST /repos/:repository/dispatches
          repository: lbryio/lbrytv-deployment
          event_type: deploy-lbrytv
          client_payload: |
            tag: ${{ steps.version.outputs.version }}
            ref: ${{ github.ref }}
            service: service-${{ steps.service.outputs.service }}
